services:
  peerbanhelper:
    image: @IMAGE@
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - /var/apps/peerbanhelper/shares/peerbanhelper:/app/data
    network_mode: host
    environment:
      - PBH_USER_LOCALE=zh-CN
      - PBH_PKG_FNOS=true
    stop_grace_period: 30s