name: fnOS Package Build

on:
  workflow_call:
    inputs:
      image:
        description: 'The image name that for build docker container'
        required: true
        type: string

jobs:
  pkgcreate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - id: java_info
        uses: YunaBraska/java-info-action@main
      - name: Run build script
        run: sudo PBH_VERSION=${{ env.PBH_VERSION }} IMAGE=${{ env.IMAGE }} bash pkg/fnos/build-script.sh
        env:
          PBH_VERSION: ${{ steps.java_info.outputs.x_version }}
          IMAGE: ${{ inputs.image }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: fnos-dist
          path: |
            pkg/fnos/target/*.zip

