name: Gradle Build

on:
  workflow_call:
    secrets:
      INSTALL4J_LICENSE:
        required: true
jobs:
  WebUI:
    uses: ./.github/workflows/build_fe.yml
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        name: Download WebUI Files
        with:
          name: webui-dist
          path: src/main/resources/static
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
          cache: 'gradle'
          cache-dependency-path: |
            gradle/wrapper/gradle-wrapper.properties
            build.gradle.kts
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Upload test results
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: test-results
          path: |
            build/reports/tests/
            build/test-results/
  Gradle:
    needs: [WebUI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        name: Download WebUI Files
        with:
          name: webui-dist
          path: src/main/resources/static
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
          cache: 'gradle'
          cache-dependency-path: |
            gradle/wrapper/gradle-wrapper.properties
            build.gradle.kts
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -x test
        env:
          JAVA_SENTRY_DSN: ${{ secrets.JAVA_SENTRY_DSN }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: gradle-dist
          path: |
            build/libraries
            build/libs/*.jar