name: Portable Package Build

on:
  workflow_call:
jobs:
  dpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - id: java_info
        uses: YunaBraska/java-info-action@main
      - uses: actions/download-artifact@v7
        with:
          name: gradle-dist
          path: build/
      - name: Build Portable package
        id: build-portable
        run: |
          mkdir -p pkg/portable/PeerBanHelper
          mv build/libraries pkg/portable/PeerBanHelper/
          cp build/libs/PeerBanHelper.jar pkg/portable/PeerBanHelper/
          cp install4j/icon.ico pkg/portable/PeerBanHelper/
          (cd pkg/portable && zip -r PeerBanHelper_${{ env.PBH_VERSION }}.zip PeerBanHelper)
          mv pkg/portable/*.bat pkg/portable/PeerBanHelper/
          (cd pkg/portable && zip -r PeerBanHelper_Windows_${{ env.PBH_VERSION }}_Portable_nojava.zip PeerBanHelper)
          mkdir -p jbr
          wget https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-25-windows-x64-b176.4.zip -O jbr/jbrsdk-25-windows-x64-b176.4.zip
          (cd jbr && unzip jbrsdk-25-windows-x64-b176.4.zip && mv jbrsdk-25-windows-x64-b176.4 jre)
          mv jbr/jre pkg/portable/PeerBanHelper/
          (cd pkg/portable && zip -r PeerBanHelper_Windows_${{ env.PBH_VERSION }}_Portable.zip PeerBanHelper)
        # 上面那个文件名需要符合收集条件
        env:
          PBH_VERSION: ${{ steps.java_info.outputs.x_version }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: portable-dist
          path: |
            pkg/portable/*.zip
