name: Maven Build

on:
  workflow_call:
    secrets:
      INSTALL4J_LICENSE:
        required: true
jobs:
  WebUI:
    uses: ./.github/workflows/build_fe.yml
  Maven:
    needs: [WebUI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v6
        name: Download WebUI Files
        with:
          name: webui-dist
          path: src/main/resources/static
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: maven-dist
          path: |
            target/libraries
            target/*.jar